name: 'github actions build and deploy gh-pages'
on: 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   // 使用 ubuntu 服务器
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1   
        with: 
          persist-credentials: false
      - name: install and build
        run: yarn && yarn run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9  // 引用别人的部署插件
        with: 
          ACCESS_TOKEN: ${{ secrets.AUTOPAGE }}   // 这里需要设置成你的 token
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
