name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2     
      - name: install
        run: |
         yarn
         yarn run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with: 
          ACCESS_TOKEN: ${{ secrets.AUTOPAGE }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
