name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.AUTOPAGE }}
        TARGET_REPO: zhizhu-video/web
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn run docs:build
        BUILD_DIR: docs/.vitepress/dist/
        CNAME: https://vite.zhizhu.video